name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      
      - name: Install aws cli
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Install openssh-client
        run: sudo apt-get install -y openssh-client

      - name: generate access key-pair
        run: |
          aws --version
      #     chmod 400 stdInfra_accessKey.pem

      # - name: create instances
      #   run: |
      #     terraform init
      #     terraform plan
      #     terraform apply -auto-approve
      #     ip_address=$(terraform output -raw ec2_ip)
      
      # - name: send .jar and docker files
      #   run: |
      #     scp -i stdInfra_accessKey.pem Dockerfile ec2-user@$ip_address:.
          

      

